### ISSUE TITLE
compilation.getAssets is not a function

### ISSUE THREAD

**Issue by hideInEye** [MQuy/webpack-deadcode-plugin#62]
webpack : 3.x
babel-loader : 6.2.4
react: 15.x
cmd : webpack --config xxx.js --watch 
执行错误,compilation.getAssets is not a function

**Comment by lisen6** [comment]
你改下他的源码就行了。compilation.getAssets 是 webpack4 才有的 api。用 compilation.assets 试试

**Comment by pavelmickevic** [comment]
seeing same with `"webpack": "^4.12.1"` 

```
 98% after emitting WebpackDeadcodePluginC:\git\myApp\node_modules\webpack-deadcode-plugin\src\detect.js:164
        compilation.getAssets().forEach(asset => {
                    ^

TypeError: compilation.getAssets is not a function
    at getWebpackAssets (C:\git\myApp\node_modules\webpack-deadcode-plugin\src\detect.js:164:14)
    at detectDeadCode (C:\git\myApp\node_modules\webpack-deadcode-plugin\src\detect.js:9:17)
    at WebpackDeadcodePlugin.handleAfterEmit (C:\git\myApp\node_modules\webpack-deadcode-plugin\src\index.js:32:3)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\git\myApp\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:14:1)
    at AsyncSeriesHook.lazyCompileHook (C:\git\myApp\node_modules\webpack\node_modules\tapable\lib\Hook.js:154:20)
    at C:\git\myApp\node_modules\webpack\lib\Compiler.js:432:27
    at C:\git\myApp\node_modules\neo-async\async.js:2813:7
    at done (C:\git\myApp\node_modules\neo-async\async.js:3521:9)
    at MemoryFileSystem.writeFile (C:\git\myApp\node_modules\memory-fs\lib\MemoryFileSystem.js:328:9)
    at writeOut (C:\git\myApp\node_modules\webpack\lib\Compiler.js:415:30)
    at Immediate.<anonymous> (C:\git\myApp\node_modules\memory-fs\lib\MemoryFileSystem.js:288:4)
    at processImmediate (internal/timers.js:464:21)
```

**Comment by 624515059** [comment]
> 你改下他的源码就行了。compilation.getAssets 是 webpack4 才有的 api。用 compilation.assets 试试

vue-cli新建个简单项目。在App.js引入部分export的常量，但是并没有识别未使用的export。
复杂项目中，反而识别了一部分。这和compilation.chunks有关🐴？

**Comment by 624515059** [comment]
@lisen6 
hi，vue-cli新建个简单项目测试了下功能：在App.js引入的同一个文件部分export的常量，但是并没有识别未使用的export。
复杂项目中，反而识别了一部分。这和打包产物compilation.chunks有关嘛？
